create table if not exists public.used_collocations (
  id bigint generated by default as identity primary key,
  collocation_id bigint not null unique references public.collocations(id) on delete cascade,
  collocation_slug text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists used_collocations_collocation_slug_idx
  on public.used_collocations (collocation_slug);

alter table public.used_collocations enable row level security;
